--1
SELECT * FROM MOVIES;

--2
SELECT * FROM GENRES;

--3
SELECT * FROM STUDIOS WHERE STUDIO_ACTIVE = 1;

--4
SELECT * FROM MEMBERS ORDER BY  MEMBER_DISCHARGE_DATE DESC LIMIT 20;

--5
SELECT MOVIE_DURATION FROM MOVIES GROUP BY MOVIE_DURATION ORDER BY COUNT(MOVIE_DURATION) DESC LIMIT 20; 

--6
SELECT * FROM MOVIES WHERE (YEAR(MOVIE_LAUNCH_DATE) > 2000) AND (MOVIE_NAME LIKE 'A%');

--7
SELECT * FROM ACTORS WHERE MONTH(ACTOR_BIRTH_DATE) = 6

--8
SELECT * FROM ACTORS WHERE (MONTH(ACTOR_BIRTH_DATE) != 6) AND (ACTOR_DEAD_DATE IS NULL);

--9
SELECT
	DIRECTOR_NAME,
	AGE
FROM
	(
	SELECT
		DIRECTOR_NAME,
		DATEDIFF(YEAR, DIRECTOR_BIRTH_DATE, TODAY()) AS "AGE",
		DIRECTOR_DEAD_DATE
	FROM
		DIRECTORS)
WHERE
	AGE <= 50
	AND DIRECTOR_DEAD_DATE IS NULL;

--10
SELECT
	ACTOR_NAME,
	AGE
FROM
	(
	SELECT
		ACTOR_NAME,
		DATEDIFF(YEAR, ACTOR_BIRTH_DATE, TODAY()) AS "AGE",
		ACTOR_DEAD_DATE
	FROM
		ACTORS)
WHERE
	AGE < 50
	AND ACTOR_DEAD_DATE IS NOT NULL;

--11
SELECT
	DIRECTOR_NAME
FROM
	(
	SELECT
		DIRECTOR_NAME,
		DATEDIFF(YEAR, DIRECTOR_BIRTH_DATE, TODAY()) AS "AGE",
		DIRECTOR_DEAD_DATE
	FROM
		DIRECTORS)
WHERE
	AGE <= 40
	AND DIRECTOR_DEAD_DATE IS NULL;

